import type { TScreenTakeover } from "./types/screen-takeover";

export const dummyByRequestType: Record<"running_text" | "vtron_text" | "vtron_photo" | "vtron_video", TScreenTakeover[]> = {
    running_text: [
        {
            id: 1,
            request_type: "running_text",
            message: "Happy birthday, Andi! 🎉",
            media_file: null,
            donation_amount: "50000",
            status: "approved",
            customer_name: "Budi",
            table_number: 3,
            reviewed_at: "2026-04-22T10:15:00Z",
            created_at: "2026-04-22T10:10:00Z",
        },
        {
            id: 2,
            request_type: "running_text",
            message: "Last order makanan pukul 23:00.",
            media_file: null,
            donation_amount: "0",
            status: "pending",
            customer_name: "Admin",
            table_number: 0,
            reviewed_at: "",
            created_at: "2026-04-22T10:20:00Z",
        },
    ],

    vtron_text: [
        {
            id: 3,
            request_type: "vtron_text",
            message: "Diskon 50% hanya malam ini!",
            media_file: null,
            donation_amount: "100000",
            status: "approved",
            customer_name: "Siti",
            table_number: 5,
            reviewed_at: "2026-04-22T10:25:00Z",
            created_at: "2026-04-22T10:22:00Z",
        },
        {
            id: 4,
            request_type: "vtron_text",
            message: "Untuk kamu di sana 😉",
            media_file: null,
            donation_amount: "30000",
            status: "pending",
            customer_name: "Fajar",
            table_number: 8,
            reviewed_at: "",
            created_at: "2026-04-22T10:30:00Z",
        },
    ],

    vtron_photo: [
        {
            id: 5,
            request_type: "vtron_photo",
            message: "Foto kenangan malam ini 📸",
            media_file: "https://example.com/media/photo1.jpg",
            donation_amount: "75000",
            status: "approved",
            customer_name: "Rizky",
            table_number: 7,
            reviewed_at: "2026-04-22T10:35:00Z",
            created_at: "2026-04-22T10:32:00Z",
        },
        {
            id: 6,
            request_type: "vtron_photo",
            message: "Cheers dari meja 1 🍻",
            media_file: "https://example.com/media/photo2.jpg",
            donation_amount: "90000",
            status: "rejected",
            customer_name: "Arif",
            table_number: 1,
            reviewed_at: "2026-04-22T10:40:00Z",
            created_at: "2026-04-22T10:38:00Z",
        },
    ],

    vtron_video: [
        {
            id: 7,
            request_type: "vtron_video",
            message: "Video spesial untuk kamu ❤️",
            media_file: "https://example.com/media/video1.mp4",
            donation_amount: "150000",
            status: "approved",
            customer_name: "Dewi",
            table_number: 2,
            reviewed_at: "2026-04-22T10:45:00Z",
            created_at: "2026-04-22T10:42:00Z",
        },
        {
            id: 8,
            request_type: "vtron_video",
            message: "Highlight party malam ini 🔥",
            media_file: "https://example.com/media/video2.mp4",
            donation_amount: "200000",
            status: "pending",
            customer_name: "Lina",
            table_number: 4,
            reviewed_at: "",
            created_at: "2026-04-22T10:50:00Z",
        },
    ],
};
