import type { TMySongReq } from "./types/song-request";

export const dummyMySongReq: TMySongReq[] = [
    {
        id: 1,
        song_title: "Perfect",
        artist: "Ed Sheeran",
        donation_amount: "50000",
        status: "pending",
        customer_name: "Andi",
        table_number: 3,
        reviewed_at: null,
        created_at: "2026-04-01T10:15:00Z",
    },
    {
        id: 2,
        song_title: "Fix You",
        artist: "Coldplay",
        donation_amount: "75000",
        status: "approved",
        customer_name: "Budi",
        table_number: 5,
        reviewed_at: null,
        created_at: "2026-04-01T11:20:00Z",
    },
    {
        id: 3,
        song_title: "Someone Like You",
        artist: "Adele",
        donation_amount: "60000",
        status: "rejected",
        customer_name: "Citra",
        table_number: 2,
        reviewed_at: null,
        created_at: "2026-04-01T12:05:00Z",
    },
    {
        id: 4,
        song_title: "Shape of You",
        artist: "Ed Sheeran",
        donation_amount: "80000",
        status: "approved",
        customer_name: "Dewi",
        table_number: 1,
        reviewed_at: null,
        created_at: "2026-04-01T13:45:00Z",
    },
    {
        id: 5,
        song_title: "All of Me",
        artist: "John Legend",
        donation_amount: "90000",
        status: "pending",
        customer_name: "Eko",
        table_number: 4,
        reviewed_at: null,
        created_at: "2026-04-01T14:30:00Z",
    },
];
